import type { CaseDocument, CaseFile, DocChunk, Evidence, Conflict, CaseHistoryEntry } from './types';

const doc1Id = 'doc-001';
const doc2Id = 'doc-002';
const doc3Id = 'doc-003';

const doc1Chunks: DocChunk[] = [
  {
    id: 'chunk-001',
    documentId: doc1Id,
    documentName: 'University Academic Regulations',
    pageNumber: 14,
    section: '4.2 Academic Eligibility',
    chunkIndex: 0,
    text: 'All undergraduate students must maintain a minimum academic percentage of 55% throughout their program of study to remain in good academic standing. Students falling below 55% will be placed on academic probation for one semester.',
  },
  {
    id: 'chunk-002',
    documentId: doc1Id,
    documentName: 'University Academic Regulations',
    pageNumber: 15,
    section: '4.3 Continuation Requirements',
    chunkIndex: 1,
    text: 'A student whose percentage falls below 50% for two consecutive semesters shall be required to withdraw from the program. Re-admission requires re-application through the standard admissions process.',
  },
  {
    id: 'chunk-003',
    documentId: doc1Id,
    documentName: 'University Academic Regulations',
    pageNumber: 8,
    section: '3.1 Grading System',
    chunkIndex: 2,
    text: 'The university uses a percentage-based grading system. Grades are calculated on a scale of 0 to 100. A grade of 55% or above is considered a passing grade for undergraduate courses.',
  },
  {
    id: 'chunk-004',
    documentId: doc1Id,
    documentName: 'University Academic Regulations',
    pageNumber: 22,
    section: '7.1 Re-examination Policy',
    chunkIndex: 3,
    text: 'Students who score between 50% and 55% may request a re-examination. Re-examination requests must be submitted within 10 working days of result publication. A fee of $50 applies per course.',
  },
];

const doc2Chunks: DocChunk[] = [
  {
    id: 'chunk-005',
    documentId: doc2Id,
    documentName: 'Scholarship Guidelines',
    pageNumber: 7,
    section: 'Eligibility Criteria',
    chunkIndex: 0,
    text: 'To be eligible for the Academic Excellence Scholarship, students must maintain a minimum academic percentage of 60% or higher. This requirement applies to all scholarship recipients for the duration of the award.',
  },
  {
    id: 'chunk-006',
    documentId: doc2Id,
    documentName: 'Scholarship Guidelines',
    pageNumber: 8,
    section: 'Scholarship Tiers',
    chunkIndex: 1,
    text: 'The Academic Excellence Scholarship has three tiers: Bronze (60-70%), Silver (70-85%), and Gold (85% and above). Each tier receives a different stipend amount ranging from $1,000 to $5,000 per semester.',
  },
  {
    id: 'chunk-007',
    documentId: doc2Id,
    documentName: 'Scholarship Guidelines',
    pageNumber: 12,
    section: 'Renewal Policy',
    chunkIndex: 2,
    text: 'Scholarship renewal is contingent upon maintaining the minimum 60% academic percentage at the end of each academic year. Students who drop below 60% forfeit their scholarship for the following semester.',
  },
  {
    id: 'chunk-008',
    documentId: doc2Id,
    documentName: 'Scholarship Guidelines',
    pageNumber: 3,
    section: 'Overview',
    chunkIndex: 3,
    text: 'The Scholarship Program is designed to recognize and reward academic achievement. All enrolled undergraduate students are automatically considered for scholarship eligibility based on their academic performance.',
  },
];

const doc3Chunks: DocChunk[] = [
  {
    id: 'chunk-009',
    documentId: doc3Id,
    documentName: 'Student Eligibility Circular',
    pageNumber: 2,
    section: 'Eligibility Requirements',
    chunkIndex: 0,
    text: 'As per the latest circular issued by the Academic Council, students below 60% academic percentage are not eligible for any form of academic recognition, scholarship, or enrollment in specialized programs.',
  },
  {
    id: 'chunk-010',
    documentId: doc3Id,
    documentName: 'Student Eligibility Circular',
    pageNumber: 3,
    section: 'Implementation Timeline',
    chunkIndex: 1,
    text: 'This circular supersedes all previous eligibility notifications and is effective from the current academic year. All departments must enforce the 60% minimum requirement for eligibility-related decisions.',
  },
  {
    id: 'chunk-011',
    documentId: doc3Id,
    documentName: 'Student Eligibility Circular',
    pageNumber: 4,
    section: 'Department Responsibilities',
    chunkIndex: 2,
    text: 'Each academic department is responsible for verifying student eligibility at the end of every semester. The verification must include percentage calculation, scholarship eligibility, and program continuation status.',
  },
  {
    id: 'chunk-012',
    documentId: doc3Id,
    documentName: 'Student Eligibility Circular',
    pageNumber: 5,
    section: 'Appeals Process',
    chunkIndex: 3,
    text: 'Students who believe they have been incorrectly deemed ineligible may file an appeal with the Academic Review Board within 15 working days. Appeals must include supporting documentation and a written statement.',
  },
];

const demoEvidence: Evidence[] = [
  {
    id: 'ev-001',
    documentId: doc1Id,
    documentName: 'University Academic Regulations',
    section: '4.2 Academic Eligibility',
    pageNumber: 14,
    statement: 'Minimum academic requirement: 55%',
    strength: 'HIGH',
    relevance: 94,
    chunkId: 'chunk-001',
  },
  {
    id: 'ev-002',
    documentId: doc2Id,
    documentName: 'Scholarship Guidelines',
    section: 'Eligibility Criteria',
    pageNumber: 7,
    statement: 'Minimum academic requirement: 60% for scholarship eligibility',
    strength: 'HIGH',
    relevance: 91,
    chunkId: 'chunk-005',
  },
  {
    id: 'ev-003',
    documentId: doc3Id,
    documentName: 'Student Eligibility Circular',
    section: 'Eligibility Requirements',
    pageNumber: 2,
    statement: 'Students below 60% are not eligible for any academic recognition',
    strength: 'HIGH',
    relevance: 89,
    chunkId: 'chunk-009',
  },
  {
    id: 'ev-004',
    documentId: doc1Id,
    documentName: 'University Academic Regulations',
    section: '3.1 Grading System',
    pageNumber: 8,
    statement: 'A grade of 55% or above is considered a passing grade',
    strength: 'MEDIUM',
    relevance: 72,
    chunkId: 'chunk-003',
  },
  {
    id: 'ev-005',
    documentId: doc2Id,
    documentName: 'Scholarship Guidelines',
    section: 'Renewal Policy',
    pageNumber: 12,
    statement: 'Scholarship renewal requires maintaining minimum 60% academic percentage',
    strength: 'HIGH',
    relevance: 85,
    chunkId: 'chunk-007',
  },
  {
    id: 'ev-006',
    documentId: doc3Id,
    documentName: 'Student Eligibility Circular',
    section: 'Implementation Timeline',
    pageNumber: 3,
    statement: 'This circular supersedes all previous eligibility notifications',
    strength: 'MEDIUM',
    relevance: 68,
    chunkId: 'chunk-010',
  },
  {
    id: 'ev-007',
    documentId: doc2Id,
    documentName: 'Scholarship Guidelines',
    section: 'Scholarship Tiers',
    pageNumber: 8,
    statement: 'Bronze tier starts at 60%, Silver at 70%, Gold at 85%',
    strength: 'MEDIUM',
    relevance: 61,
    chunkId: 'chunk-006',
  },
  {
    id: 'ev-008',
    documentId: doc1Id,
    documentName: 'University Academic Regulations',
    section: '4.3 Continuation Requirements',
    pageNumber: 15,
    statement: 'Students below 50% for two consecutive semesters must withdraw',
    strength: 'MEDIUM',
    relevance: 55,
    chunkId: 'chunk-002',
  },
];

const demoConflicts: Conflict[] = [
  {
    id: 'conflict-001',
    topic: 'Minimum Academic Percentage',
    claims: [
      {
        source: 'University Academic Regulations',
        documentId: doc1Id,
        value: '55%',
        section: '4.2 Academic Eligibility',
        pageNumber: 14,
      },
      {
        source: 'Scholarship Guidelines',
        documentId: doc2Id,
        value: '60%',
        section: 'Eligibility Criteria',
        pageNumber: 7,
      },
      {
        source: 'Student Eligibility Circular',
        documentId: doc3Id,
        value: '60% (supersedes prior notifications)',
        section: 'Eligibility Requirements',
        pageNumber: 2,
      },
    ],
    difference: '5 percentage points between regulatory minimum and scholarship/eligibility requirement',
    status: 'UNRESOLVED',
    description:
      'The University Academic Regulations specify 55% as the minimum passing percentage, while both the Scholarship Guidelines and the Student Eligibility Circular require 60%. The Circular claims to supersede prior notifications, but the Regulations have not been formally updated.',
  },
];

const demoDocuments: CaseDocument[] = [
  {
    id: doc1Id,
    name: 'University_Academic_Regulations.pdf',
    type: 'PDF',
    pages: 24,
    extractionStatus: 'EXTRACTED',
    indexingStatus: 'INDEXED',
    evidenceCount: 4,
    investigationStatus: 'READY',
    chunks: doc1Chunks,
    uploadDate: '2026-10-01T10:00:00Z',
  },
  {
    id: doc2Id,
    name: 'Scholarship_Guidelines.pdf',
    type: 'PDF',
    pages: 15,
    extractionStatus: 'EXTRACTED',
    indexingStatus: 'INDEXED',
    evidenceCount: 3,
    investigationStatus: 'READY',
    chunks: doc2Chunks,
    uploadDate: '2026-10-01T10:01:00Z',
  },
  {
    id: doc3Id,
    name: 'Student_Eligibility_Circular.txt',
    type: 'TXT',
    pages: 6,
    extractionStatus: 'EXTRACTED',
    indexingStatus: 'INDEXED',
    evidenceCount: 3,
    investigationStatus: 'READY',
    chunks: doc3Chunks,
    uploadDate: '2026-10-01T10:02:00Z',
  },
];

export const demoCase: CaseFile = {
  id: 'case-001',
  number: '#001',
  title: 'THE ELIGIBILITY MYSTERY',
  description: 'Investigate the minimum academic percentage required across university regulations, scholarship guidelines, and eligibility circulars.',
  status: 'INVESTIGATING',
  documents: demoDocuments,
  conflicts: demoConflicts,
  evidence: demoEvidence,
  investigations: [],
  confidence: 'CONFLICTED',
  createdDate: '2026-10-01T10:00:00Z',
};

export const caseHistory: CaseHistoryEntry[] = [
  {
    id: 'case-001',
    number: '#001',
    title: 'Eligibility Investigation',
    documentCount: 3,
    conflictCount: 1,
    status: 'INVESTIGATING',
    date: '2026-10-01',
    confidence: 'CONFLICTED',
  },
  {
    id: 'case-002',
    number: '#002',
    title: 'Scholarship Requirement Investigation',
    documentCount: 5,
    conflictCount: 0,
    status: 'COMPLETED',
    date: '2026-09-28',
    confidence: 'VERIFIED',
  },
  {
    id: 'case-003',
    number: '#003',
    title: 'Grading Policy Review',
    documentCount: 4,
    conflictCount: 2,
    status: 'COMPLETED',
    date: '2026-09-25',
    confidence: 'CONFLICTED',
  },
  {
    id: 'case-004',
    number: '#004',
    title: 'Examination Rules Analysis',
    documentCount: 2,
    conflictCount: 0,
    status: 'COMPLETED',
    date: '2026-09-20',
    confidence: 'SUPPORTED',
  },
];

export const suggestedQuestions: string[] = [
  'What is the minimum academic percentage required?',
  'Which document defines eligibility?',
  'Are there conflicting requirements?',
  'Which source is more recent?',
  'What evidence supports this conclusion?',
];
